const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Behaviors.LOS,
		C3.Behaviors.Turret,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Космос: 0},
	{Фон: 0},
	{Фізика: 0},
	{ТвердеТіло: 0},
	{Стіни: 0},
	{Швидкість: 0},
	{ШвидкістьПовороту: 0},
	{Ривок: 0},
	{ХП: 0},
	{ОбмежитиРівнем: 0},
	{ЗнищитиПозаРівнем: 0},
	{СлідкуватиЗа: 0},
	{Гравець: 0},
	{Клавіатура: 0},
	{Якір: 0},
	{Енергія: 0},
	{Урон: 0},
	{Куля1: 0},
	{ХПгравця: 0},
	{Шкода: 0},
	{ВорогМіна: 0},
	{Текст: 0},
	{Прикріплення: 0},
	{ЗнищенняПозаРівнем: 0},
	{Діаманта2: 0},
	{Діаманта: 0},
	{Спрайт3: 0},
	{Спрайт7: 0},
	{Миша: 0},
	{ПошукШляху: 0},
	{Спрайт: 0},
	{чіти: 0},
	{Спрайт2: 0},
	{Спрайт4: 0},
	{Куля2: 0},
	{бали: 0},
	{Аудіо: 0},
	{Текст2: 0},
	{Кнопка: 0},
	{Куля: 0},
	{Всі_Кулі: 0},
	{ПолеЗору: 0},
	{Вороги: 0},
	{Турель2: 0},
	{Турель: 0},
	{бал: 0}
];

self.InstanceType = {
	Космос: class extends self.ITiledBackgroundInstance {},
	Фон: class extends self.ITilemapInstance {},
	Стіни: class extends self.ITilemapInstance {},
	Гравець: class extends self.ISpriteInstance {},
	Клавіатура: class extends self.IInstance {},
	Енергія: class extends self.ISpriteInstance {},
	Куля1: class extends self.ISpriteInstance {},
	ХПгравця: class extends self.ISpriteInstance {},
	ВорогМіна: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Діаманта2: class extends self.ISpriteInstance {},
	Діаманта: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	чіти: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Куля2: class extends self.ISpriteInstance {},
	бали: class extends self.ITextInstance {},
	Аудіо: class extends self.IInstance {},
	Текст2: class extends self.ITextInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Всі_Кулі: class extends self.ISpriteInstance {},
	Вороги: class extends self.ISpriteInstance {},
	Турель: class extends self.ISpriteInstance {}
}