const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Behaviors.LOS,
		C3.Behaviors.Turret,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Button.Cnds.OnCreated,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Космос: 0},
	{Фон: 0},
	{Фізика: 0},
	{ТвердеТіло: 0},
	{Стіни: 0},
	{Швидкість: 0},
	{ШвидкістьПовороту: 0},
	{Ривок: 0},
	{ХП: 0},
	{ОбмежитиРівнем: 0},
	{ЗнищитиПозаРівнем: 0},
	{СлідкуватиЗа: 0},
	{Гравець: 0},
	{Клавіатура: 0},
	{Якір: 0},
	{Енергія: 0},
	{Урон: 0},
	{Куля1: 0},
	{ХПгравця: 0},
	{Шкода: 0},
	{ВорогМіна: 0},
	{Текст: 0},
	{Прикріплення: 0},
	{ЗнищенняПозаРівнем: 0},
	{BEEEEEEEEEE: 0},
	{BEEEEEEEEEE2: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Миша: 0},
	{Спрайт3: 0},
	{КнопкасСтарт: 0},
	{Кнопка2: 0},
	{Текст2: 0},
	{Текст3: 0},
	{LOAD: 0},
	{ПошукШляху: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{КнопкаМеню: 0},
	{Thanos_Player_Picture: 0},
	{Кнопка3: 0},
	{Текст4: 0},
	{Текст5: 0},
	{Текст6: 0},
	{Game_Logo: 0},
	{Twisted_Glisten_Render: 0},
	{images2: 0},
	{Куля2: 0},
	{Куляворога: 0},
	{ТекстБали: 0},
	{сек: 0},
	{Pebble_Render: 0},
	{download: 0},
	{Спрайт4: 0},
	{УламокМіни: 0},
	{download2: 0},
	{download3: 0},
	{download4: 0},
	{download5: 0},
	{Аудіо: 0},
	{Текст7: 0},
	{images: 0},
	{Спрайт7: 0},
	{ЦІНА: 0},
	{Блимання: 0},
	{свибірСкіна: 0},
	{Спрайт9: 0},
	{Текст8: 0},
	{Спрайт10: 0},
	{Кнопка: 0},
	{магазин: 0},
	{Куля: 0},
	{Всі_Кулі: 0},
	{ПолеЗору: 0},
	{Вороги: 0},
	{Турель: 0},
	{Turrets: 0},
	{бали: 0},
	{секунда: 0},
	{скін: 0}
];

self.InstanceType = {
	Космос: class extends self.ITiledBackgroundInstance {},
	Фон: class extends self.ITilemapInstance {},
	Стіни: class extends self.ITilemapInstance {},
	Гравець: class extends self.ISpriteInstance {},
	Клавіатура: class extends self.IInstance {},
	Енергія: class extends self.ISpriteInstance {},
	Куля1: class extends self.ISpriteInstance {},
	ХПгравця: class extends self.ISpriteInstance {},
	ВорогМіна: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	BEEEEEEEEEE: class extends self.ISpriteInstance {},
	BEEEEEEEEEE2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	КнопкасСтарт: class extends self.IButtonInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	Текст2: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {},
	LOAD: class extends self.IButtonInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	КнопкаМеню: class extends self.IButtonInstance {},
	Thanos_Player_Picture: class extends self.ISpriteInstance {},
	Кнопка3: class extends self.IButtonInstance {},
	Текст4: class extends self.ITextInstance {},
	Текст5: class extends self.ITextInstance {},
	Текст6: class extends self.ITextInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Twisted_Glisten_Render: class extends self.ISpriteInstance {},
	images2: class extends self.ISpriteInstance {},
	Куляворога: class extends self.ISpriteInstance {},
	ТекстБали: class extends self.ITextInstance {},
	сек: class extends self.ITextInstance {},
	Pebble_Render: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	УламокМіни: class extends self.ISpriteInstance {},
	download2: class extends self.ISpriteInstance {},
	download3: class extends self.ISpriteInstance {},
	download4: class extends self.ISpriteInstance {},
	download5: class extends self.ISpriteInstance {},
	Аудіо: class extends self.IInstance {},
	Текст7: class extends self.ITextInstance {},
	images: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	свибірСкіна: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст8: class extends self.ITextInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Кнопка: class extends self.IButtonInstance {},
	магазин: class extends self.IButtonInstance {},
	Всі_Кулі: class extends self.ISpriteInstance {},
	Вороги: class extends self.ISpriteInstance {},
	Turrets: class extends self.ISpriteInstance {}
}