const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Behaviors.LOS,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Behaviors.Turret,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Button.Cnds.OnCreated,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Космос: 0},
	{Фон: 0},
	{Фізика: 0},
	{ТвердеТіло: 0},
	{Стіни: 0},
	{Швидкість: 0},
	{ШвидкістьПовороту: 0},
	{Ривок: 0},
	{ХП: 0},
	{ОбмежитиРівнем: 0},
	{ЗнищитиПозаРівнем: 0},
	{СлідкуватиЗа: 0},
	{Гравець: 0},
	{Клавіатура: 0},
	{Якір: 0},
	{Енергія: 0},
	{Урон: 0},
	{Куля1: 0},
	{ХПгравця: 0},
	{Шкода: 0},
	{ВорогМіна: 0},
	{Текст: 0},
	{Прикріплення: 0},
	{ЗнищенняПозаРівнем: 0},
	{ВогникГравця: 0},
	{"2ВогникГравця2": 0},
	{Спрайт: 0},
	{Миша: 0},
	{пріціл: 0},
	{ПошукШляху: 0},
	{Куля: 0},
	{ПолеЗору2: 0},
	{ворогРозумний: 0},
	{КуляВорога: 0},
	{КнопкаРівень1: 0},
	{Спрайт2: 0},
	{Текст2: 0},
	{КнопкаПрод: 0},
	{Спрайт3: 0},
	{КнопкаМеню: 0},
	{Спрайт4: 0},
	{УЛАМКИМІНИ: 0},
	{ТекстбАЛИ: 0},
	{Текст3: 0},
	{Текст4: 0},
	{Текст5: 0},
	{Текст6: 0},
	{Текст7: 0},
	{Аудіо: 0},
	{Текст8: 0},
	{КнопкаМагаз: 0},
	{Спрайт5: 0},
	{Ціна: 0},
	{Блимання: 0},
	{ВибірСкіна: 0},
	{ТекстнаМагазині: 0},
	{вихід: 0},
	{Текст9: 0},
	{КнопкаЗберегтиГру: 0},
	{Спрайт6: 0},
	{Текст10: 0},
	{Всі_Кулі: 0},
	{ПолеЗору: 0},
	{Вороги: 0},
	{Турель: 0},
	{турель: 0},
	{БАЛИ: 0},
	{скін: 0}
];

self.InstanceType = {
	Космос: class extends self.ITiledBackgroundInstance {},
	Фон: class extends self.ITilemapInstance {},
	Стіни: class extends self.ITilemapInstance {},
	Гравець: class extends self.ISpriteInstance {},
	Клавіатура: class extends self.IInstance {},
	Енергія: class extends self.ISpriteInstance {},
	Куля1: class extends self.ISpriteInstance {},
	ХПгравця: class extends self.ISpriteInstance {},
	ВорогМіна: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	ВогникГравця: class extends self.ISpriteInstance {},
	_2ВогникГравця2: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	пріціл: class extends self.ISpriteInstance {},
	ворогРозумний: class extends self.ISpriteInstance {},
	КуляВорога: class extends self.ISpriteInstance {},
	КнопкаРівень1: class extends self.IButtonInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	КнопкаПрод: class extends self.IButtonInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	КнопкаМеню: class extends self.IButtonInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	УЛАМКИМІНИ: class extends self.ISpriteInstance {},
	ТекстбАЛИ: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {},
	Текст4: class extends self.ITextInstance {},
	Текст5: class extends self.ITextInstance {},
	Текст6: class extends self.ITextInstance {},
	Текст7: class extends self.ITextInstance {},
	Аудіо: class extends self.IInstance {},
	Текст8: class extends self.ITextInstance {},
	КнопкаМагаз: class extends self.IButtonInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	ВибірСкіна: class extends self.ISpriteInstance {},
	ТекстнаМагазині: class extends self.ITextInstance {},
	вихід: class extends self.ISpriteInstance {},
	Текст9: class extends self.ITextInstance {},
	КнопкаЗберегтиГру: class extends self.IButtonInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Текст10: class extends self.ITextInstance {},
	Всі_Кулі: class extends self.ISpriteInstance {},
	Вороги: class extends self.ISpriteInstance {},
	турель: class extends self.ISpriteInstance {}
}